"""pyrmallet.py.

A PyRMallet-backed implementation of the topic-modeling API used by Lexos.
This class mirrors the public API contract of the Java MALLET-backed `Mallet`
class while delegating training to the `pyrmallet` package when available.

Last Updated: September 8, 2026
Last Tested: September 8, 2026
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, ClassVar, Optional

import numpy as np
from pydantic import ConfigDict, Field, model_validator
from tqdm.auto import tqdm
from wasabi import msg

from lexos.exceptions import LexosException
from lexos.topic_modeling.mallet.mallet import MALLET_BINARY_PATH, Mallet

try:
    from pyrmallet import LatentDirichletAllocation
except Exception:  # pragma: no cover - optional dependency
    LatentDirichletAllocation = None  # type: ignore[assignment]


class PyRMallet(Mallet):
    """A MALLET-compatible wrapper backed by PyRMallet.

    This class intentionally mirrors the public API and metadata contract of the
    Java MALLET implementation, but delegates training/inference to the
    `pyrmallet` package. Existing downstream code can work without changes,
    because the class stores the same canonical metadata keys and writes the same
    output file conventions as `Mallet`.
    """

    backend: str = "pyrmallet"
    model_config = ConfigDict(arbitrary_types_allowed=True)

    path_to_mallet: str = MALLET_BINARY_PATH
    model_dir: Optional[Path | str] = Field(
        None,
        description="The directory where the model is stored.",
    )
    metadata: dict[str, Any] = Field(
        {},
        description="A dict containing metadata generated by the class instance.",
    )

    CANONICAL_DOC_TOPIC_KEY: ClassVar[str] = "path_to_topic_distributions"
    CANONICAL_TERM_WEIGHTS_KEY: ClassVar[str] = "path_to_term_weights"
    CANONICAL_TOPIC_KEYS_KEY: ClassVar[str] = "path_to_topic_keys"
    CANONICAL_INFERENCER_KEY: ClassVar[str] = "path_to_inferencer"

    def __init__(self, **data: Any):
        """Initialize the PyRMallet class."""
        super().__init__(**data)

    @model_validator(mode="after")
    def _validate_backend(self) -> "PyRMallet":
        """Ensure PyRMallet is installed and configured."""
        if LatentDirichletAllocation is None:
            raise LexosException(
                "PyRMallet is not installed. Install it with `pip install pyrmallet`."
            )
        return self

    def _write_training_data(
        self, training_data: list[str], path_to_training_data: str
    ) -> None:
        """Persist training docs in the same format expected by the MALLET API.

        Args:
            training_data: A list of document strings to be persisted.
            path_to_training_data: The file path where the training data should be written.
        """
        with open(path_to_training_data, "w", encoding="utf-8") as fh:
            for i, doc in enumerate(training_data):
                clean = str(doc).replace("\r", " ").replace("\n", " ").strip()
                fh.write(f"{i}\tno_label\t{clean}\n")

    def _write_doc_topic_file(
        self, path: str, probabilities: list[list[float]]
    ) -> None:
        """Write one dense probability vector per document to match MALLET output.

        Args:
            path: The file path where the document-topic distributions should be written.
            probabilities: A list of lists containing the topic probabilities for each document.

        MALLET `doc-topic.txt` stores each document as a single line with the
        document id, label, and a full topic distribution. Writing one line per
        topic would make downstream calls such as `get_top_docs()` misread the
        file and think each row is the full distribution even when the model has
        many topics.
        """
        if not probabilities:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write("#doc\tlabel\n")
            return

        num_topics = len(probabilities[0])
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(
                "#doc\tlabel\t" + "\t".join(str(i) for i in range(num_topics)) + "\n"
            )
            for doc_idx, dist in enumerate(probabilities):
                values = [str(doc_idx), str(doc_idx)] + [str(float(v)) for v in dist]
                fh.write("\t".join(values) + "\n")

    def _write_topic_keys_file(
        self,
        path: str,
        topic_word_matrix: np.ndarray,
        feature_names: list[str],
        topic_weights: Optional[list[float]] = None,
    ) -> None:
        """Write topic keys in the same simple format MALLET expects.

        Args:
            path: The file path where the topic keys should be written.
            topic_word_matrix: A 2D NumPy array representing the topic-word distributions.
            feature_names: A list of feature names corresponding to the columns of the topic-word matrix.
            topic_weights: Optional list of topic weights. If not provided, the sum of the term probabilities for each topic will be used.

        The MALLET `topic-keys.txt` format stores the topic weight in the second
        column, which is the mean document-topic probability for that topic, not
        the sum of the term probabilities for the keywords row.
        """
        weights = topic_weights or [float(row.sum()) for row in topic_word_matrix]
        with open(path, "w", encoding="utf-8") as fh:
            for topic_idx, row in enumerate(topic_word_matrix):
                top_terms = []
                for term_idx in np.argsort(row)[::-1][:10]:
                    top_terms.append(feature_names[term_idx])
                keywords = " ".join(top_terms)
                fh.write(f"{topic_idx}\t{float(weights[topic_idx]):.12f}\t{keywords}\n")

    def _write_term_weights_file(
        self, path: str, topic_word_matrix: np.ndarray, feature_names: list[str]
    ) -> None:
        """Write a MALLET-style topic-word weights file.

        Args:
            path: The file path where the topic-word weights should be written.
            topic_word_matrix: A 2D NumPy array representing the topic-word distributions.
            feature_names: A list of feature names corresponding to the columns of the topic-word matrix.
        """
        with open(path, "w", encoding="utf-8") as fh:
            for topic_idx, row in enumerate(topic_word_matrix):
                for term_idx, weight in enumerate(row):
                    if weight <= 0:
                        continue
                    fh.write(
                        f"{topic_idx}\t{feature_names[term_idx]}\t{float(weight):.12f}\n"
                    )

    @staticmethod
    def _as_float_list(values: Any) -> list[list[float]]:
        """Convert NumPy arrays to plain floats with the shape expected by callers.

        Args:
            values: The input values to be converted to a list of lists of floats.

        Returns:
            A list of lists of floats with the same shape as the input.
        """
        arr = np.asarray(values, dtype=float)
        return arr.tolist()

    @staticmethod
    def _compatibility_stopwords(remove_stopwords: bool) -> list[str] | None:
        """Translate Lexos stopword behavior into the PyRMallet stopwords parameter.

        Args:
            remove_stopwords: A boolean indicating whether to remove stopwords.

        Returns:
            A list of stopwords if `remove_stopwords` is True, otherwise None.
        """
        if not remove_stopwords:
            return None
        # Use the standard English stopword list shipped by the runtime as the
        # closest compatibility default for the MALLET `--remove-stopwords` flag.
        try:
            from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

            return sorted(ENGLISH_STOP_WORDS)
        except Exception:
            return []

    @staticmethod
    def _compatibility_vocab_filters() -> dict[str, Any]:
        """Keep PyRMallet pruning defaults aligned with the no-op MALLET behavior.

        Returns:
            A dictionary containing the default vocabulary filter settings for PyRMallet.
        """
        return {"min_doc_freq": 1, "max_doc_fraction": 1.0}

    def _build_lda(
        self,
        num_topics: int,
        num_iterations: int,
        verbose: bool,
        remove_stopwords: bool,
        optimize_interval: Optional[int],
    ) -> Any:
        """Create the underlying PyRMallet LDA instance with compatibility defaults.

        Args:
            num_topics: The number of topics to be extracted by the LDA model.
            num_iterations: The number of iterations for the LDA training process.
            verbose: A boolean indicating whether to enable verbose output during training.
            remove_stopwords: A boolean indicating whether to remove stopwords.
            optimize_interval: An optional integer specifying the interval for optimizing the model.

        Returns:
            An instance of the PyRMallet LDA model configured with the specified parameters.
        """
        if LatentDirichletAllocation is None:
            raise LexosException("PyRMallet is not installed.")

        stopwords = self._compatibility_stopwords(remove_stopwords)
        vocab_filters = self._compatibility_vocab_filters()
        return LatentDirichletAllocation(
            n_components=num_topics,
            max_iter=num_iterations,
            verbose=verbose,
            stopwords=stopwords,
            min_doc_freq=vocab_filters["min_doc_freq"],
            max_doc_fraction=vocab_filters["max_doc_fraction"],
            optimize_interval=optimize_interval or 0,
        )

    def _fit_lda(
        self, lda: Any, training_data: list[str], num_iterations: int, verbose: bool
    ) -> Any:
        """Fit the LDA model while preserving the existing progress behavior.

        Args:
            lda: The LDA model instance to be fitted.
            training_data: A list of training documents represented as strings.
            num_iterations: The number of iterations for the LDA training process.
            verbose: A boolean indicating whether to enable verbose output during training.

        Returns:
            The fitted LDA model instance.
        """
        if verbose:
            with tqdm(
                total=max(int(num_iterations), 1),
                desc="Training model",
                leave=True,
            ) as pbar:
                lda.fit(training_data)
                pbar.n = max(int(num_iterations), 1)
                pbar.set_description("Complete")
                pbar.refresh()
            return lda

        lda.fit(training_data)
        return lda

    def _normalize_model_arrays(
        self,
        lda: Any,
        training_data: list[str],
        num_topics: int,
    ) -> tuple[list[list[float]], np.ndarray, list[str]]:
        """Extract and normalize the model arrays back into MALLET-compatible shapes.

        Args:
            lda: The fitted LDA model instance.
            training_data: A list of training documents represented as strings.
            num_topics: The number of topics in the LDA model.

        Returns:
            A tuple containing the document-topic distributions, topic-word distributions, and the list of feature names.
        """
        doc_topic = self._as_float_list(
            getattr(
                lda,
                "doc_topic_distributions_",
                np.zeros((len(training_data), num_topics)),
            )
        )
        topic_word = np.asarray(
            getattr(lda, "components_", np.zeros((num_topics, 1))), dtype=float
        )
        feature_names = list(
            getattr(lda, "feature_names_in_", np.array([], dtype=object))
        )
        if not feature_names and training_data:
            feature_names = sorted(
                {token for doc in training_data for token in doc.split()}
            )
        if len(feature_names) == 0:
            feature_names = [f"token_{idx}" for idx in range(topic_word.shape[1])]

        if topic_word.shape[0] != num_topics:
            topic_word = np.resize(
                topic_word, (num_topics, max(1, topic_word.shape[1]))
            )
        if topic_word.shape[1] != len(feature_names):
            pad_width = max(0, len(feature_names) - topic_word.shape[1])
            if pad_width:
                topic_word = np.pad(
                    topic_word, ((0, 0), (0, pad_width)), mode="constant"
                )

        return doc_topic, topic_word, feature_names

    def _write_model_outputs(
        self,
        doc_topic: list[list[float]],
        topic_word: np.ndarray,
        feature_names: list[str],
        num_topics: int,
    ) -> tuple[str, str, str, str, list[float]]:
        """Persist the standard MALLET artifact files and return the metadata paths.

        Args:
            doc_topic: The document-topic distributions.
            topic_word: The topic-word distributions.
            feature_names: The list of feature names corresponding to the columns of the topic-word matrix.
            num_topics: The number of topics in the LDA model.

        Returns:
            A tuple containing the paths to the topic distributions file, topic keys file, term weights file, inferencer file, and the list of topic weights.
        """
        path_to_topic_distributions = str(Path(self.model_dir) / "doc-topic.txt")
        path_to_topic_keys = str(Path(self.model_dir) / "topic-keys.txt")
        path_to_term_weights = str(Path(self.model_dir) / "topic-weights.txt")
        path_to_inferencer = str(Path(self.model_dir) / "inferencer.mallet")
        topic_weights = (
            np.asarray(doc_topic, dtype=float).mean(axis=0).tolist()
            if doc_topic
            else [1.0 / num_topics] * num_topics
        )

        self._write_doc_topic_file(path_to_topic_distributions, doc_topic)
        self._write_topic_keys_file(
            path_to_topic_keys,
            topic_word,
            feature_names,
            topic_weights,
        )
        self._write_term_weights_file(path_to_term_weights, topic_word, feature_names)

        return (
            path_to_topic_distributions,
            path_to_topic_keys,
            path_to_term_weights,
            path_to_inferencer,
            topic_weights,
        )

    def _train_backend(
        self,
        training_data: list[str],
        num_topics: int,
        num_iterations: int,
        verbose: bool,
        remove_stopwords: bool = True,
        optimize_interval: Optional[int] = 10,
    ) -> None:
        """Train a model with PyRMallet and write MALLET-compatible outputs.

        Args:
            training_data: The list of training documents represented as strings.
            num_topics: The number of topics in the LDA model.
            num_iterations: The number of iterations for training the LDA model.
            verbose: Whether to print verbose output during training.
            remove_stopwords: Whether to remove stopwords from the training data.
            optimize_interval: The interval at which to optimize hyperparameters during training.
        """
        lda = self._build_lda(
            num_topics=num_topics,
            num_iterations=num_iterations,
            verbose=verbose,
            remove_stopwords=remove_stopwords,
            optimize_interval=optimize_interval,
        )
        lda = self._fit_lda(lda, training_data, num_iterations, verbose)

        doc_topic, topic_word, feature_names = self._normalize_model_arrays(
            lda, training_data, num_topics
        )
        (
            path_to_topic_distributions,
            path_to_topic_keys,
            path_to_term_weights,
            path_to_inferencer,
            topic_weights,
        ) = self._write_model_outputs(
            doc_topic,
            topic_word,
            feature_names,
            num_topics,
        )

        self.metadata[self.CANONICAL_DOC_TOPIC_KEY] = path_to_topic_distributions
        self.metadata[self.CANONICAL_TOPIC_KEYS_KEY] = path_to_topic_keys
        self.metadata[self.CANONICAL_TERM_WEIGHTS_KEY] = path_to_term_weights
        self.metadata[self.CANONICAL_INFERENCER_KEY] = path_to_inferencer
        self.metadata["num_topics"] = num_topics
        self.metadata["num_iterations"] = num_iterations
        self.metadata["training_model"] = "pyrmallet"
        self.metadata["feature_names_in_"] = list(feature_names)

        with open(Path(self.model_dir) / "meta.json", "w") as fh:
            fh.write(json.dumps(self.metadata))

        self.metadata["doc_topic_distributions_"] = doc_topic
        self.metadata["components_"] = topic_word.tolist()
        self.metadata["feature_names_in_"] = feature_names
        self.metadata["topic_weights_"] = topic_weights

        if verbose:
            msg.good("PyRMallet training complete")

    def _import_training_data(
        self,
        training_data: list[str],
        path_to_training_data: Optional[str] = None,
        keep_sequence: bool = True,
        remove_stopwords: bool = True,
        preserve_case: bool = True,
        use_pipe_from: Optional[str] = None,
        training_ids: Optional[list[int]] = None,
    ) -> None:
        """Mirror the training-data import contract used by the Java MALLET backend.

        Args:
            training_data: The list of training documents represented as strings.
            path_to_training_data: The path to the file where the training data will be written.
            keep_sequence: Whether to keep the original token sequence in the training data.
            remove_stopwords: Whether to remove stopwords from the training data.
            preserve_case: Whether to preserve the original case of the tokens.
            use_pipe_from: The path to an existing MALLET pipe to use for preprocessing.
            training_ids: Optional list of training document IDs.
        """
        path_to_training_data = (
            path_to_training_data
            if path_to_training_data is not None
            else str(Path(self.model_dir) / "training_data.txt")
        )
        self._write_training_data(training_data, path_to_training_data)

        self.metadata["path_to_training_data"] = path_to_training_data
        self.metadata["path_to_formatted_training_data"] = str(
            Path(self.model_dir) / "training_data.mallet"
        )
        self.metadata["num_docs"] = len(training_data)
        self.metadata["vocab_size"] = len(
            {token for doc in training_data for token in doc.split()}
        )
        self.metadata["mean_num_tokens"] = (
            sum(len(doc.split()) for doc in training_data) / len(training_data)
            if training_data
            else 0
        )

        with open(Path(self.model_dir) / "meta.json", "w") as fh:
            fh.write(json.dumps(self.metadata))

    @staticmethod
    def _convert_docs_to_training_list(docs: list[str] | Path | str) -> list[str]:
        """Normalize the docs argument to a list of raw strings.

        Args:
            docs: The input documents, which can be a list of strings, a path to a file, or a Path object.

        Returns:
            A list of raw document strings.

        Raises:
            LexosException: If the input is not a valid list of strings or a path to a file.
        """
        if isinstance(docs, (Path, str)) and Path(docs).is_file():
            with open(docs, "r", encoding="utf-8") as fh:
                return [line.rstrip("\n") for line in fh if line.strip()]
        if isinstance(docs, bool) or not isinstance(docs, list):
            raise LexosException(
                "Invalid `docs` argument: expected a list of strings or a path to a file."
            )
        for doc in docs:
            if isinstance(doc, bool) or not isinstance(doc, str):
                raise LexosException(
                    "Invalid `docs` element: expected document text (str) for each item."
                )
        return docs

    def import_data(
        self,
        training_data: list[str],
        path_to_training_data: str = None,
        keep_sequence: bool = True,
        preserve_case: bool = True,
        remove_stopwords: bool = True,
        use_pipe_from: Optional[str] = None,
        training_ids: Optional[list[int]] = None,
    ) -> None:
        """Import data for training with the PyRMallet backend.

        Args:
            training_data: The list of training documents represented as strings.
            path_to_training_data: The path to the file where the training data will be written.
            keep_sequence: Whether to keep the original token sequence in the training data.
            preserve_case: Whether to preserve the original case of the tokens.
            remove_stopwords: Whether to remove stopwords from the training data.
            use_pipe_from: The path to an existing MALLET pipe to use for preprocessing.
            training_ids: Optional list of training document IDs.
        """
        if isinstance(training_data, bool) or not isinstance(training_data, list):
            raise LexosException(
                "Invalid `training_data` argument: expected a list of document strings."
            )
        for doc in training_data:
            if isinstance(doc, bool) or not isinstance(doc, str):
                raise LexosException(
                    "Invalid `training_data` element: expected document text (str) for each item."
                )

        if not path_to_training_data:
            model_base = Path(self.model_dir) if self.model_dir else Path.cwd()
            path_to_training_data = str(model_base / "training_data.txt")

        self._import_training_data(
            training_data,
            path_to_training_data,
            keep_sequence,
            remove_stopwords,
            preserve_case,
            use_pipe_from,
            training_ids,
        )

    def train(
        self,
        num_topics: int = 20,
        num_iterations: Optional[int] = 100,
        optimize_interval: Optional[int] = 10,
        verbose: Optional[bool] = True,
        path_to_state: Optional[str] = None,
        path_to_topic_keys: Optional[str] = None,
        path_to_topic_distributions: Optional[str] = None,
        path_to_term_weights: Optional[str] = None,
        path_to_diagnostics: Optional[str] = None,
        path_to_inferencer: Optional[str] = None,
    ) -> None:
        """Train using PyRMallet while writing MALLET-compatible output files.

        Args:
            num_topics: The number of topics to generate.
            num_iterations: The number of iterations for training.
            optimize_interval: The interval for optimizing hyperparameters.
            verbose: Whether to print verbose output during training.
            path_to_state: The path to the file where the topic state will be written.
            path_to_topic_keys: The path to the file where the topic keys will be written.
            path_to_topic_distributions: The path to the file where the document-topic distributions will be written.
            path_to_term_weights: The path to the file where the topic-term weights will be written.
            path_to_diagnostics: The path to the file where the diagnostics will be written.
            path_to_inferencer: The path to the file where the inferencer will be written.
        """
        if not self.model_dir:
            raise LexosException("A model_dir must be set before training.")

        if "path_to_training_data" not in self.metadata:
            raise LexosException(
                "No training data has been set. Call `import_data()` or `import_file()` before training."
            )

        with open(self.metadata["path_to_training_data"], "r", encoding="utf-8") as fh:
            training_data = [
                line.strip().split("\t", 2)[-1] for line in fh if line.strip()
            ]

        if path_to_topic_keys is None:
            path_to_topic_keys = str(Path(self.model_dir) / "topic-keys.txt")
        if path_to_topic_distributions is None:
            path_to_topic_distributions = str(Path(self.model_dir) / "doc-topic.txt")
        if path_to_term_weights is None:
            path_to_term_weights = str(Path(self.model_dir) / "topic-weights.txt")
        if path_to_inferencer is None:
            path_to_inferencer = str(Path(self.model_dir) / "inferencer.mallet")

        self.metadata[self.CANONICAL_DOC_TOPIC_KEY] = path_to_topic_distributions
        self.metadata[self.CANONICAL_TOPIC_KEYS_KEY] = path_to_topic_keys
        self.metadata[self.CANONICAL_TERM_WEIGHTS_KEY] = path_to_term_weights
        self.metadata[self.CANONICAL_INFERENCER_KEY] = path_to_inferencer

        self._train_backend(
            training_data=training_data,
            num_topics=num_topics,
            num_iterations=num_iterations or 100,
            verbose=bool(verbose),
            remove_stopwords=True,
            optimize_interval=optimize_interval,
        )

        self.metadata["training_command"] = [
            "pyrmallet",
            "LatentDirichletAllocation",
            f"n_components={num_topics}",
            f"max_iter={num_iterations}",
        ]
        self.metadata["num_topics"] = num_topics
        self.metadata["num_iterations"] = num_iterations
        self.metadata["n_inference_iter"] = 50
        self.metadata["optimize_interval"] = optimize_interval
        self.metadata["path_to_state"] = path_to_state or str(
            Path(self.model_dir) / "topic-state.gz"
        )
        self.metadata["path_to_diagnostics"] = path_to_diagnostics or str(
            Path(self.model_dir) / "diagnostics.xml"
        )

        with open(Path(self.model_dir) / "meta.json", "w") as fh:
            fh.write(json.dumps(self.metadata))

    def infer(
        self,
        docs: list[str] | Path | str,
        path_to_inferencer: Optional[str | Path] = None,
        output_path: Optional[str | Path] = None,
        keep_sequence: bool = True,
        preserve_case: bool = True,
        remove_stopwords: bool = True,
        use_pipe_from: Optional[str | Path] = None,
        show: bool = False,
    ) -> list[list[float]] | None:
        """Infer topic distributions for docs using the PyRMallet backend.

        Args:
            docs: The list of documents to infer topics for, or a path to a file containing the documents.
            path_to_inferencer: The path to the inferencer file to use for inference.
            output_path: The path to the file where the inferred document-topic distributions will be written.
            keep_sequence: Whether to keep the original token sequence in the inference data.
            preserve_case: Whether to preserve the original case of the tokens.
            remove_stopwords: Whether to remove stopwords from the inference data.
            use_pipe_from: The path to an existing MALLET pipe to use for preprocessing.
            show: Whether to display the inferred topic distributions instead of returning them.
        """
        docs_list = self._convert_docs_to_training_list(docs)
        if path_to_inferencer is None:
            path_to_inferencer = self._metadata_get([self.CANONICAL_INFERENCER_KEY])
        if path_to_inferencer is None:
            raise LexosException(
                "No inferencer has been set. Provide `path_to_inferencer` or set it in metadata when training."
            )

        stopwords = self._compatibility_stopwords(remove_stopwords)
        vocab_filters = self._compatibility_vocab_filters()
        inference_iterations = int(self.metadata.get("n_inference_iter", 50))
        lda = LatentDirichletAllocation(
            n_components=int(self.metadata.get("num_topics", 10)),
            stopwords=stopwords,
            min_doc_freq=vocab_filters["min_doc_freq"],
            max_doc_fraction=vocab_filters["max_doc_fraction"],
            n_inference_iter=inference_iterations,
        )
        lda.fit(self.metadata.get("training_data", docs_list))
        distributions = self._as_float_list(lda.transform(docs_list))

        if output_path is None:
            output_path = str(Path(self.model_dir) / "infer-doc-topics.txt")
        self._write_doc_topic_file(str(output_path), distributions)

        if show:
            return None
        return distributions

    def set_metadata(self, parameter: str, value: Any) -> None:
        """Set a metadata value and persist it to disk.

        Args:
            parameter: The name of the metadata parameter to set.
            value: The value to set for the metadata parameter.
        """
        self.metadata[parameter] = value
        with open(Path(self.model_dir) / "meta.json", "w") as fh:
            fh.write(json.dumps(self.metadata))


__all__ = ["PyRMallet"]
